package com.myspace.nps;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer Account")
@org.kie.api.definition.type.Description("Customer Account with NPS Details")
public class Account implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Contact Record Status")
	private java.lang.String contactRecordStatus;

	@org.kie.api.definition.type.Label("Contact Email Verification Status")
	private java.lang.String contactEmail;

	@org.kie.api.definition.type.Label("Most Recent Interaction")
	private java.time.LocalDate recentInteraction;

	@org.kie.api.definition.type.Label("Lease Status")
	private java.lang.String leaseStatus;

	@org.kie.api.definition.type.Label("Most Recen tPayment")
	private int recentPayment;

	@org.kie.api.definition.type.Label("Bankruptcy Flagged")
	private java.lang.String bankruptcy;

	@org.kie.api.definition.type.Label("Lease Term")
	private int leaseTerm;

	@org.kie.api.definition.type.Label("Renewal Opportunity")
	private int renewal;

	@org.kie.api.definition.type.Label("Send Survey")
	private boolean sendSurvey;

	@org.kie.api.definition.type.Label(value = "Contact Record Condition")
	private boolean contactRecordCondn;

	@org.kie.api.definition.type.Label(value = "Contact Email Verification Status Condition")
	private boolean contactEmailCondn;

	@org.kie.api.definition.type.Label(value = "Most Recent Interaction Condition")
	private boolean recentInteractionCondn;

	@org.kie.api.definition.type.Label(value = "Lease Status Condition")
	private boolean leaseStatusCondn;

	@org.kie.api.definition.type.Label(value = "Most Recent Payment Condition")
	private boolean recentPaymentCondn;

	@org.kie.api.definition.type.Label(value = "Bankruptcy Flagged Condition")
	private boolean bankruptcyCondn;

	@org.kie.api.definition.type.Label(value = "Lease Term Condition")
	private boolean leaseTermCondn;

	@org.kie.api.definition.type.Label(value = "Renewal Opportunity Condition")
	private boolean renewalCondn;

	public Account() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getContactRecordStatus() {
		return this.contactRecordStatus;
	}

	public void setContactRecordStatus(java.lang.String contactRecordStatus) {
		this.contactRecordStatus = contactRecordStatus;
	}

	public java.lang.String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(java.lang.String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public java.time.LocalDate getRecentInteraction() {
		return this.recentInteraction;
	}

	public void setRecentInteraction(java.time.LocalDate recentInteraction) {
		this.recentInteraction = recentInteraction;
	}

	public java.lang.String getLeaseStatus() {
		return this.leaseStatus;
	}

	public void setLeaseStatus(java.lang.String leaseStatus) {
		this.leaseStatus = leaseStatus;
	}

	public java.lang.String getBankruptcy() {
		return this.bankruptcy;
	}

	public void setBankruptcy(java.lang.String bankruptcy) {
		this.bankruptcy = bankruptcy;
	}

	public int getLeaseTerm() {
		return this.leaseTerm;
	}

	public void setLeaseTerm(int leaseTerm) {
		this.leaseTerm = leaseTerm;
	}

	public boolean isSendSurvey() {
		return this.sendSurvey;
	}

	public void setSendSurvey(boolean sendSurvey) {
		this.sendSurvey = sendSurvey;
	}

	public int getRecentPayment() {
		return this.recentPayment;
	}

	public void setRecentPayment(int recentPayment) {
		this.recentPayment = recentPayment;
	}

	public int getRenewal() {
		return this.renewal;
	}

	public void setRenewal(int renewal) {
		this.renewal = renewal;
	}

	public boolean isContactRecordCondn() {
		return this.contactRecordCondn;
	}

	public void setContactRecordCondn(boolean contactRecordCondn) {
		this.contactRecordCondn = contactRecordCondn;
	}

	public boolean isContactEmailCondn() {
		return this.contactEmailCondn;
	}

	public void setContactEmailCondn(boolean contactEmailCondn) {
		this.contactEmailCondn = contactEmailCondn;
	}

	public boolean isRecentInteractionCondn() {
		return this.recentInteractionCondn;
	}

	public void setRecentInteractionCondn(boolean recentInteractionCondn) {
		this.recentInteractionCondn = recentInteractionCondn;
	}

	public boolean isLeaseStatusCondn() {
		return this.leaseStatusCondn;
	}

	public void setLeaseStatusCondn(boolean leaseStatusCondn) {
		this.leaseStatusCondn = leaseStatusCondn;
	}

	public boolean isRecentPaymentCondn() {
		return this.recentPaymentCondn;
	}

	public void setRecentPaymentCondn(boolean recentPaymentCondn) {
		this.recentPaymentCondn = recentPaymentCondn;
	}

	public boolean isBankruptcyCondn() {
		return this.bankruptcyCondn;
	}

	public void setBankruptcyCondn(boolean bankruptcyCondn) {
		this.bankruptcyCondn = bankruptcyCondn;
	}

	public boolean isLeaseTermCondn() {
		return this.leaseTermCondn;
	}

	public void setLeaseTermCondn(boolean leaseTermCondn) {
		this.leaseTermCondn = leaseTermCondn;
	}

	public boolean isRenewalCondn() {
		return this.renewalCondn;
	}

	public void setRenewalCondn(boolean renewalCondn) {
		this.renewalCondn = renewalCondn;
	}

	public Account(java.lang.Long id, java.lang.String contactRecordStatus,
			java.lang.String contactEmail,
			java.time.LocalDate recentInteraction,
			java.lang.String leaseStatus, int recentPayment,
			java.lang.String bankruptcy, int leaseTerm, int renewal,
			boolean sendSurvey, boolean contactRecordCondn,
			boolean contactEmailCondn, boolean recentInteractionCondn,
			boolean leaseStatusCondn, boolean recentPaymentCondn,
			boolean bankruptcyCondn, boolean leaseTermCondn,
			boolean renewalCondn) {
		this.id = id;
		this.contactRecordStatus = contactRecordStatus;
		this.contactEmail = contactEmail;
		this.recentInteraction = recentInteraction;
		this.leaseStatus = leaseStatus;
		this.recentPayment = recentPayment;
		this.bankruptcy = bankruptcy;
		this.leaseTerm = leaseTerm;
		this.renewal = renewal;
		this.sendSurvey = sendSurvey;
		this.contactRecordCondn = contactRecordCondn;
		this.contactEmailCondn = contactEmailCondn;
		this.recentInteractionCondn = recentInteractionCondn;
		this.leaseStatusCondn = leaseStatusCondn;
		this.recentPaymentCondn = recentPaymentCondn;
		this.bankruptcyCondn = bankruptcyCondn;
		this.leaseTermCondn = leaseTermCondn;
		this.renewalCondn = renewalCondn;
	}

}